language: php

php:
  - 5.6
  - 7.0

before_install:
  - pip install --user codecov

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install

script:
  - gulp
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov
