language: php

php:
  - 5.5
  - 5.6

before_install:
  - pip install --user git+https://github.com/codecov/codecov-python.git@aa451c4c9984ef422a9151baf941fc422ce8d396

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
