language: php

php:
  - 5.5
  - 5.6

before_install:
  - pip install --user codecov

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
#  - codecov
