language: php

php:
  - 5.5
  - 5.6
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  
before_install:
  - pip install --user codecov
after_success:
  - codecov
  
